title: QuarkSpin Blog
email: quarkspin@tutanota.com
description: >- # this means to ignore newlines until "baseurl:"
  Réflexion et curiosité
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://quarkspin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/images/icon_blue.svg"
twitter_username: QuarkSpin1
github_username:  QuarkSpin

# Credits
author:
  name: Nicolas Maurice
  picture: /images/nicolas.png
  twitter: QuarkSpin1
  email: quarkspin@tutanota.com
  links:
    - title: Twitter
      url: https://twitter.com/QuarkSpin1
      icon: fab fa-twitter
    - title: GitHub
      url: https://github.com/QuarkSpin
      icon: fab fa-github

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Liquid
liquid:
  error_mode: strict

# Theme
theme: jekyll-theme-so-simple
skin: "/assets/css/skins/default.css"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Locale
locale: fr-FR
date_format: "%d/%m/%Y"

# Reading time
read_time: true
words_per_minute: 200

# Maths
mathjax:
  enable: true             # MathJax equations, e.g. true, false (default)
  combo: "tex-svg"         # "tex-svg" (default), "tex-mml-chtml", etc.
  tags: "ams"              # "none", "ams" (default), "all"

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/QuarkSpin
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/QuarkSpin
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square