title: QuarkSpin
email: quarkspin@tutanota.com
description: Réflexion et curiosité
logo: "/images/icon_blue.svg"
twitter_username: QuarkSpin42
github_username:  QuarkSpin

# URL
baseurl: "/blog"
url: "https://quarkspin.github.io"
permalink: /:year-:month-:day/:title/

# Analytics
google_analytics: G-2S0N51NS35

# Credits
author:
  name: Nicolas Maurice
  picture: /images/nicolas.jpg
  twitter: QuarkSpin42
  email: quarkspin@tutanota.com
  links:
    - title: Twitter
      url: https://twitter.com/QuarkSpin42
      icon: fab fa-twitter
    - title: GitHub
      url: https://github.com/QuarkSpin
      icon: fab fa-github

copyright: "© 2020–2021 Nicolas Maurice — Articles sous license [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.fr){: target=\"_blank\"}"

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Liquid
liquid:
  error_mode: strict

# Navigation
category_archive_path: "/categories/#"
tag_archive_path: "/sujets/#"

# Theme
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/default.css"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Locale
locale: fr-FR
date_format: "%d/%m/%Y"

# Reading time
read_time: true
words_per_minute: 200

# Maths
mathjax:
  enable: true             # MathJax equations, e.g. true, false (default)
  combo: "tex-svg"         # "tex-svg" (default), "tex-mml-chtml", etc.
  tags: "ams"              # "none", "ams" (default), "all"

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/QuarkSpin42
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/QuarkSpin
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square